### ISSUE TITLE
Ignored devices function not working

### ISSUE THREAD

**Issue by stlouey** [bwp91/homebridge-platform-wemo#219]
### What issue do you have? Please be as thorough and explicit as possible.
Have added a device serial number to ignore/remove from homebridge via the settings option yet the devices is still listed under accessories in homebridge ui and ios homekit. restarted homebridge and server os with no effect. Have triple checked serial via wemo app and the device itself.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Yes use homebridge ui-x

* Which version of Homebridge/HOOBS do you have?

v4.35.0

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?

v2.5.0. Not sure when issue started as i have just tried with the versions listed.

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

maker F7C043fc

### Please paste any relevant logs below.

```
nothing listed at all in logs regarding the maker???
```

**Comment by bwp91** [comment]
Hi @stlouey 
Could you try removing the serial number from the ignored devices list, let it be discovered by the plugin, then add the serial number back to see if this removes the device?
If this doesn't work, then could you post the wemo section of your config json file here?
Thanks

**Comment by stlouey** [comment]
Hi Ben,

I think I know what the issue is and its in relation to this device not being online and ignored in my wemo app. Regardless of being ignored in the wemo app the plugin is still listing/finding it and is not able to remove it until its back online and then ignored. I had to find it and turn it on so the plugin log showed it found it and then I was able to add the serial and then restart for it to now be removed/hidden.

A couple thing to share:


  1.  [device name] not found yet so cannot be controlled. Will retry connection. (this is how it showed up and could not be removed as per my original issue. What would have happened if I sold the device and or it was faulty? I would not be able to remove it and it takes a tile on my limited view on iPhone home screen. I am aware I could have requested to have it removed from cloud.
  2.  When the maker was found it showed in the log as this: [12/5/2020, 7:28:22 PM] [WeMo Platform] [device name] found with serial number [x] and mac address [x]. HAP Warning: Characteristic 0000006A-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.

B.T.W do you know why when renaming a device in wemo app all is ok but the plugin will always lists its original first name and never any further rename?

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwp91** [comment]
Hi @stlouey 

First of all, just to clarify that there is no synchronisation of devices between the wemo app and the homebridge plugin, as the wemo app uses the cloud, and the plugin uses local network discovery. Meaning:

* If you ignore/remove a device from the wemo app, this change will not be reflected in homebridge (or vice versa)
* If you change a device's name from the wemo app, this will not be updated in homebridge (or vice versa)

>  [device name] not found yet so cannot be controlled. Will retry connection. (this is how it showed up and could not be removed as per my original issue. What would have happened if I sold the device and or it was faulty? I would not be able to remove it and it takes a tile on my limited view on iPhone home screen. I am aware I could have requested to have it removed from cloud.

Once any device has been discovered by the plugin **once**, then you can use the "ignored devices" setting to remove and add as you wish. 

* to ignore (and remove) a device which remains plugged-in and connected to your local network, the serial number will need to remain in the list

* to ignore (and remove) a device which for example has been sold, faulty, or just not in use (ie not plugged in), the serial number just needs to go in the list once (so the plugin knows to remove it) and then can be removed from the list again. The device would be added back to Homebridge if it were ever discovered again (ie plugged back in one day)

There are also different methods to remove a device from Homebridge:

* Using the "Remove Accessory from Cache" feature of config-ui-x (recommended way)
* Using the "Disable Plugin" plugin setting (although this will indeed remove _all_ devices so a last resort)
* Manually editing the `cachedAccessories` file (although advanced so not recommended)

For the reasons mentioned above, removing the device from the cloud would not have automatically removed this device from Homebridge.

> When the maker was found it showed in the log as this: [12/5/2020, 7:28:22 PM] [WeMo Platform] [device name] found with serial number [x] and mac address [x]. HAP Warning: Characteristic 0000006A-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.

This is indeed an issue with the code that I have overlooked. I don't own the maker myself, so as with a lot of device types I rely on user feedback. In fact I'm surprised this hasn't been noticed before. This will be fixed in a version that I plan to release today.

> B.T.W do you know why when renaming a device in wemo app all is ok but the plugin will always lists its original first name and never any further rename?

The 'Wemo' name of any device will be used as the Homebridge name when it is added initially. From then on, device names are independent of platform (Wemo app, Homebridge, Home app). Indeed the logs will always show the original name of a device, even if it is renamed in any of the platforms.

If you wish for the logs to show an updated name for a device then you will need to add the device to the ignore list (so it is removed from homebridge) and then remove it again so the device is re-added.

**Comment by stlouey** [comment]
Hi Ben,

Do you know what this means in the log:

Subscription still pending for uuid:Bridge

All my bulbs now have been discovered with the serial and mac of the bridge with this message below each discovered address? I think this has happened after LINK reboot and obviously can not remove further devices properly.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwp91** [comment]
Ah. If you are trying to add bulbs to the ignore list, then you will need to specify the device id of each bulb, rather than the serial number of the wemo link.
In v2.6.1 (just released), I have changed the startup logging slightly for the link-bulbs so that it's easier to obtain the device ids. The logs will now show:

```
[accessory name] found with device id [##bulb-device-id##] and mac address [##] (link s/n [##]).
```

where, naturally, the `##bulb-device-id##` is what needs to be added to the ignore list.

It might help me to know your objective here, are you looking for a way to remove _all_ your wemo accessories from Homebridge?

**Comment by stlouey** [comment]
Hi Ben,

My objective was to remove the devices no longer on my network from showing on the limited number of widgets on the Apple iOS swipe up Control Centre for HomeKit as they were useless.

Homebridge was listing these devices even after removing the cache accessories file. Under accessories I was going into each device to find serial and then adding them to be removed but they would not.

What worked for me after your email was that I had to find all the old devices and plug them for the plugin to find them and then I had to add them and or add them remove them re add them for it to work.

Would be nice would be to just check a button to have them removed, anyway my current issue is that after trying to get all devices to be available to be found (like restart wemo link) I now get the issue where the plugin on restart lists all wemo bulbs with the same serial and mac of the wemo link and I get the following text under each bulb found:

Subscription still pending for uuid:Bridge

Just wanted to also ay thanks for your support so far on this issue.

Regards

Stephen


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwp91** [comment]
> Would be nice would be to just check a button to have them removed

There is the option in config-ui-x to do this. Removing a single cached accessory is possible.

> anyway my current issue is that after trying to get all devices to be available to be found (like restart wemo link) I now get the issue where the plugin on restart lists all wemo bulbs with the same serial and mac of the wemo link and I get the following text under each bulb found:

Have you updated to v2.6.1? This should show the individual device ID of each bulb in the logs on startup. This device ID can be added to the ignored devices list in the same was as a standard device serial number. Once they have been removed from the cache then the `Subscription still pending for uuid:Bridge` will not appear.

Perhaps using config-ui-x to remove each bulb from the accessory cache would be the most straightforward method?

Thanks

**Comment by stlouey** [comment]
Ben,

I setup homebridge+config-ui-x  using hb-service and how have the settings to remove accessories. I removed everything as they had old name and they were all rediscovered with their new names but still get the following error for a few bulbs that are live:

12/7/2020, 10:12:51 PM] [WeMo Platform] [Lamp] added to Homebridge with serial number [undefined] and mac address [undefined].
[12/7/2020, 10:12:51 PM] [WeMo Platform] [Lamp] found with device id [94103EF6BF429DD5] and mac address [C0:56:27:B1:98:48] (link s/n [231531B0100306]).
[12/7/2020, 10:12:51 PM] [WeMo Platform] Subscription still pending for uuid:Bridge-1_0-231531B0100306.

Thanks

Stephen

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwp91** [comment]
Does the `Subscription still pending` message repeat itself in the logs continually? Or does it just appear after a Homebridge restart a couple of times?
Are the bulbs controllable through Home app?

**Comment by stlouey** [comment]
It only shows 3 times under 3 devices when your start/restart, this is the same order for every restart. Did you notice the device that I showed was added with and undefined serial and mac?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bwp91** [comment]
> It only shows 3 times under 3 devices when your start/restart, this is the same order for every restart.

I think the plugin is taking slightly longer to connect to the wemo link than other devices. If it appears just once or twice then this is nothing to worry about.

> Did you notice the device that I showed was added with and undefined serial and mac?

Yes, this is purely a 'cosmetic' issue with the logging. Something I have fixed a few moments ago, but nothing that will have affected the workings of the plugin.

**Comment by jweber93** [comment]
"[device name] not found yet so cannot be controlled. Will retry connection." was being logged every few min as well for me.  Removing the device from the homebridge cache and restarting seems to have fixed it.  Removing and adding the device back to the ignored list (and restarting in-between) seemingly didn't do anything.

**Comment by bwp91** [comment]
> Removing and adding the device back to the ignored list (and restarting in-between) seemingly didn't do anything.

Was the device discovered by the plugin after removing it from the ignored list? This is required for this method to work, otherwise (eg if you don't have the device anymore) then removing the device from the HB cache would be the required method.

**Comment by jweber93** [comment]
> Was the device discovered by the plugin after removing it from the ignored list? 

Yes, the device was still being discovered (I still have it).

**Comment by bwp91** [comment]
Out of interest, if you added the device to the ignore list again, rebooted HB, is it removed?
With the latest version I cannot reproduce the scenario when a device is **not** removed from HB after it being added to the ignore list

**Comment by jweber93** [comment]
I can't recall if I saw it completely removed.  My only testing/validation was looking for the error line, which was there before and after putting the device in the ignored list.
