### ISSUE TITLE
Any way to get this plugin to automatically find plugs with multiple vlans?

### ISSUE THREAD

**Issue by MatthewGCampbell** [bwp91/homebridge-platform-wemo#220]
Is their any way to get homebridge to automatically find plugs that are one a different vlan other than homebridge? I can get to homebridge on all vlans, just it won’t find my wemo plugs with them being on a different vlan.

**Comment by bwp91** [comment]
Hi @MatthewGCampbell 

I think the best way forward would be giving the devices static IPs from your router and using the "manual devices" configuration option.

This can be set up in the plugin settings (via config-ui) in the "Manual Devices" section, or editing the config json directly with the following:

```
"manualDevices": [
  "http://192.168.1.20:49153/setup.xml",
  "http://192.168.1.21:49153/setup.xml",
  ...
],
```

The only things that need to be changed are (obviously!) the IP of each device, and perhaps the port. The required port for these devices is normally 49153, but can sometimes be 49152 or 49154. You can check by visiting the url in the browser and you'll see an xml file.

Hope this helps!

**Comment by MatthewGCampbell** [comment]
How about something like this and just change the port to either 49153 or 49152 or 49154
```
"wemoClient": {
                "port": 1234,
                "discover_opts": {
                    "unicastBindPort": 1235
                },
                "listen_interface": "eth0.332"
```

**Comment by bwp91** [comment]
@MatthewGCampbell you’ll need to add “http://“ to the manual devices

**Comment by MatthewGCampbell** [comment]
Ah forgot about that thanks, I set them all to static IPs still wondering a their is a way you could get the discovery thing working on multiple interfaces

Thanks, Matthew

**Comment by bwp91** [comment]
With regards to
```
"wemoClient": {
   "port": 1234,
   "discover_opts": {
      "unicastBindPort": 1235
   },
   "listen_interface": "wlan0"
}
```
The three options here `port`, `discover_opts` and `listen_interface` are independent of each other, meaning you can supply just one or two of them if needed. There are a few options you can pass to the `discover_opts` argument, for reference here is a list (taken from [npmjs.com/node-ssdp](https://www.npmjs.com/package/node-ssdp#client), it's only just become apparent to me that `unicastBindPort` isn't in the list. I took over this plugin a couple of months ago, and the `wemoClient` options are something I still haven't explored or played with!

* `interfaces` (String[]) List of interfaces to explicitly bind. By default, bind to all available interfaces.
* `explicitSocketBind` (Boolean) Bind sockets to each discovered interface explicitly instead of relying on the system. Might help with issues with multiple NICs.
* `customLogger` (Function) A logger function to use instead of the default. The first argument to the function can contain a format string.
* `reuseAddr` (Boolean) When true socket.bind() will reuse the address, even if another process has already bound a socket on it. Default: true

**Comment by MatthewGCampbell** [comment]
It didn’t seem to find the plugs but I’d be happy to be your beta tester

Thanks

**Comment by MatthewGCampbell** [comment]
Ok finally got it working hope i can help out the community, also adding it to your documentation would be cool:

{
            "name": "Wemo",
            "debug": true,
            "disableDiscovery": false,
            "discoveryInterval": 30,
            "disableDeviceLogging": false,
            "disablePlugin": false,
            "noMotionTimer": 60,
            "doorOpenTimer": 20,
            "makerTypes": [
                {
                    "makerTimer": 20
                }
            ],
            "wemoClient": {
                "port": 49135,
                "discover_opts": {
                    "explicitSocketBind": true
                },
                "listen_interface": "eth0.332, eth0.25"
            },
            "platform": "BelkinWeMo"
        }

**Comment by bwp91** [comment]
Can I invite you to my discord server to talk about this a bit more? This is a good find!
https://discord.gg/cMGhNtZ3tW

**Comment by MatthewGCampbell** [comment]
Also getting these errors but it seems to work. 
![Uploading Screen Shot 2020-12-07 at 1.53.32 PM.png…]()
