### ISSUE TITLE
Constant dropout of specific device

### ISSUE THREAD

**Issue by Movieaholic** [bwp91/homebridge-platform-wemo#249]
Hi i have many wemo devices, plugs, switches, motion sensors etc but one thing constantly bugs me whenever i change settings on my wifi or there is a power cut everything connects back to wifi and most devices end up linking with homebridge and working through homekit but there are always one or 2 that just don't want to be reliable last time this happened i had 2 lights that needed a reset daily to reconnect to homebridge so i gave them a full reset one ended up connecting properly but the other needs resets constantly to get homekit control working, I dont think there is a drop in wifi it just gets disconnected from homebridge for some reason. Any idea what i could do to get the issue resolved?

I get these errors every 60 seconds
connection error: connect ECONNREFUSED 2.1.1.62:49153 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16).

**Comment by bwp91** [comment]
Hi @Movieaholic 

One of the slight issues with wemo devices when they reset (eg after a power cut) is that the port that they use for the connection can change. The `ECONNREFUSED` error is often due to the plugin trying to connect to the wrong port.

Out of interest, how have you configured the plugin to search for devices? Do you leave the plugin to discover them automatically or do you have the devices configured manually?

In the new version of the plugin (currently in beta), I have tried to solve this problem further by always trying to search for a select the correct port for a device. Would you be happy to give this beta version a try? You can see a guide to install beta versions depending on platform [here](https://github.com/bwp91/homebridge-platform-wemo/wiki/Beta-Version).

Let me know how you get on.

Thanks

**Comment by Movieaholic** [comment]
Hi, Thanks for the reply Ive got manual devices set mainly because when I first Installed it I had the wemo devices on a seperate subnet from the homebridge device and i found device discovery didnt work at all.  Is using automatic discovery likely to fix my issue?

**Comment by bwp91** [comment]
If your devices are still on the separate subnet then you’ll most likely still need to configure manually. You could try and change from using the full address (eg. http://IP:PORT/setup.xml) to just the IP. This will try make the plugin try to obtain the port automatically.

So for each device remove the http:// and :PORT/setup.xml from the config

**Comment by Movieaholic** [comment]
I Changed to the same subnet once the 2nd version came out because the motion sensors no longer worked correctly on a different subnet anyway ive changed to auto discovery and so far no dropouts fingers crossed it resumes

**Comment by bwp91** [comment]
Any further issues with this? I'll mark this issue as complete but if you have problems just reply on here to let me know :)
