### ISSUE TITLE
Seeing a bunch of "connection error: EHOSTUNREACH" messages in logs

### ISSUE THREAD

**Issue by starlessblack** [bwp91/homebridge-platform-wemo#250]
### What issue do you have? Please be as thorough and explicit as possible.

For at least a couple versions now of the homebridge-platform-wemo plugin, I've been seeing a lot of these not-quite-errors related the plugin communicating with the plugs and then trying reconnection later. I don't really get what the possible issue is, as I am experiencing no noticeable problems controlling the plugs from Homebridge/from the end-user perspective.

Is this a case of the Wemo plugs disconnecting frequently from the network due to how they're programmed in firmware? Would lengthening the platform-wemo plugin's refresh interval in settings potentially lessen these errors? 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Config-Ui

* Which version of Homebridge/HOOBS do you have?

1.34

* Which version of this plugin (homebridge-platform-wemo) do you have? Has the issue started since upgrading from a previous version?

2.15.2

* Which Wemo devices do you have that are causing issues? Please include product models if applicable.

Wemo Mini plugs

### Please paste any relevant logs below.

```
4/10/2021, 9:15:35 AM] [WeMo Platform] [http://192.168.1.8:49153/setup.xml] connection error: connect EHOSTUNREACH 192.168.1.8:49153 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16).
Apr 10 09:16:01 raspberrypi homebridge[14762]: [4/10/2021, 9:16:01 AM] [WeMo Platform] [Wemo Plug Name] awaiting (re)connection and will retry in 30s.
Apr 10 09:16:05 raspberrypi homebridge[14762]: [4/10/2021, 9:16:05 AM] [WeMo Platform] [http://192.168.1.8:49153/setup.xml] connection error: connect EHOSTUNREACH 192.168.1.8:49153 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16).

```

**Comment by bwp91** [comment]
Hi @starlessblack a bit of a background explanation might help understand what's going on.

First, the plugin uses a upnp connection method to 'listen' for device updates and this needs to be refreshed every 300 seconds. This value is something I have never changed/experimented with since I took ownership of the plugin as basically it seems to work. The `EHOSTUNREACH` warning is can be due to:

* the device going offline (even just temporarily) or 
* in cases when a user manually configures the devices using an IP, and this IP changes

This connection is separate from actually controlling a device via HomeKit (which is an http request), so even if the upnp connection isn't established, device control from HomeKit can still work (which is most likely what is happening in your situation).

If the upnp connection isn't established then the problem occurs when 'externally' controlling the device (by this I mean via the wemo app or physically)... then this update won't be updated in HomeKit.

With regards to the logging... this is where my thoughts are split.

The advantage of the logging is that users are aware there is a issue with the connection (before, I trialled lessening the logging and I had a few users asking me what was going in mainly in cases where the connection failure was for an extended period of time).

The disadvantage of the logging is that, yes, it seems silly when the 'issue' is rectified by the plugin on the next refresh interval.

> Is this a case of the Wemo plugs disconnecting frequently from the network due to how they're programmed in firmware? 

Not sure. The only thing I can say is that I own a wemo smart plug myself and I never have connection issues shown in the logs.

> Would lengthening the platform-wemo plugin's refresh interval in settings potentially lessen these errors?

Errors like the `EHOSTUNREACH` are shown in the logs from within the 300 second connection interval, and are attempted to be rectified by the plugin on the separate refresh interval defined in the settings, so for this reason I recommend the configurable refresh interval to be less, not more (as errors get rectified sooner).

I am currently working on v3 of the plugin and I can have another look into how the plugin logs its errors. My ideas are currently either to show them in plugin debug mode, or perhaps only after the plugin notices a particular problem is ongoing (after a particular amount of time).

**Comment by starlessblack** [comment]
Thank you very much for that informative answer!

I’ve had DHCP reservation IP’s for all my Wemo plugs along with manually defined device list array in this plugin for years. But these verbose logs and your long explanation had me going back to check my configuration.

Lo and behold, I’d had the wrong MAC address in the DHCP reservation for one of the plugs this whole time!

Logs are looking much better now, so I can certainly put my issue to rest. I’d say you should probably keep this level of logging.

**Comment by bwp91** [comment]
Ah i see, glad you got it to work!
I plan to make a wiki page with these “common” errors so this `EHOSTUNREACH` will be straight on the list! Hopefully this page will be of use to future users who experience the same problems.
