### ISSUE TITLE
Wemo lights connection issues

### ISSUE THREAD

**Issue by pjbarnett** [bwp91/homebridge-platform-wemo#261]
Im on the latest version but I have intermittent errors on some plugs. They come up saying awaiting reconnection in status however they work perfectly fine from the Wemo app.

Is there something I can do to sort more permanently? If I restart the Homebridge they come back in, sometimes only for a little while, sometimes for a few days.

**Comment by bwp91** [comment]
Hi @pjbarnett 

Are you talking about the wemo light switch? or dimmer? or bulb via link?

There should be a message in the log to initially show the error, the reason for the disconnection. This should appear immediately before the first “awaiting reconnection” log entry. Are you able to get this at all?

Thanks

**Comment by pjbarnett** [comment]
Oddly no other warning. Starts with this message on restart of Homebridge:-

[6/26/2021, 9:32:30 AM] [Wemo] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW

Then further down:-

[6/26/2021, 9:33:01 AM] [Wemo] [Decking Lts] awaiting (re)connection and will retry in 30s.
[6/26/2021, 9:33:01 AM] [Wemo] [Hall Twinkles] awaiting (re)connection and will retry in 30s.

However and oddly they are now working fine at the moment. I will keep my eye on the log if they fail again. But I can guarantee they always work from the Wemo app when they are not working on Homebridge.

Thanks. I'll update if I spot anything.

**Comment by bwp91** [comment]
Before the “setup complete” log line, is there a message like
[Wemo] [Decking Lts] initialised with… ?

If not, then the plugin is struggling to find the devices on your network.

Do you have these devices configured with a manual IP?

The wemo app uses a cloud connection, the homebridge plugin uses a different local connection which is why can work through the wemo app but not homebridge. This is also the reason why wemo credentials are not needed by the plugin. This local connection works well on a “standard” network setup, but can be not so great if devices are on a different subnet.
